core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),

    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
]

dashboard/urls.py
from django.urls import path

from .views import DashboardListView

app_name="dashboard"

urlpatterns = [
    path('', DashboardListView.as_view(), name='dash'),
]

dashboard/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import redirect
from django.views.generic import View
from django.shortcuts import render, redirect



class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'new_index.html', context)
        

dashboard/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.

class DashboardListView(View):

    def get(self,request, *args, **kwargs):
        context = {
            
        }
        return render(request, 'new_dashboard.html', context)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOLA COMO ESTAS?</h1>
</body>
</html>

templates/new_index.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
        crossorigin="anonymous">
        <title>Mapas de resultados</title>  

    </head>
  

    <body>
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'dashboard:dash' %}">Dashboard</a>
    
            <div class="navbar-nav">
                <div class="nav-item text-nowrap">
                    <a class="nav-link px-3" href="#">Sign out</a>
                </div>
            </div>
    
        </header>


        <main>
            <div class="container py-3">
                <h1 class="display-4 fw-normal text-center pb-2">Opciones de mapeo</h1>
    
                <div class="d-grid gap-2 pt-2 d-md-block">
    
                    <div class="row row-cols-1 justify-content-md-center">
    
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_resultados" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_resultados">Resultados</label>
                        </div>
                        
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_tipo_territorio" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_tipo_territorio">Tipo de territorio</label>
                        </div>
    
    
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_comparativo" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_comparativo">Comparativo</label>
                        </div>
    
    
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_tipo_voto" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_tipo_voto">Tipo de voto</label>
                        </div>
    
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_gyp" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_gyp">Ganadores y Perdedores</label>
                        </div>
    
    
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_distancia" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_distancia">Distancia con el resultado</label>
                        </div>
    
                        <div class="col col-lg-6 d-flex pb-2 flex-column">
                            <input type="radio" class="btn-check" name="btnradio" id="btnradio_potencial" autocomplete="off">
                            <label class="btn btn-outline-primary" for="btnradio_potencial">Potencial crecimiento</label>
                        </div>

                    </div>  
    
       
                </div>
      
                <div class="row row-cols-1 row-cols-md-3 pt-4 mb-3 text-center">
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-1">
                                <h4 class="my-0 fw-normal">Nivel Nacional</h4>
                            </div>
                            <div class="card-body">
                                <img class="card-img-top" src="./assets/arg.png" alt="">
    
                                <p class="text-center fs-6 mt-3 mb-4">
                                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima, eius esse! Nesciunt illum non quam.
                                </p>
    
                                <div class="d-grid gap-2 d-md-block">
                                    <div class="row row-cols-2 justify-content-md-center">
                                        <div class="col d-flex pb-2 flex-column">
                                            <input type="radio" class="btn-check" name="btnradio_nivel_nacional" id="btnradio_arg_provincial" autocomplete="off">
                                            <label class="btn btn-outline-secondary" for="btnradio_arg_provincial">Por provincial</label>
                                        </div>
                                        <div class="col d-flex pb-2 flex-column">
                                            <input type="radio" class="btn-check" name="btnradio_nivel_nacional" id="btnradio_arg_departamental" autocomplete="off">
                                            <label class="btn btn-outline-secondary" for="btnradio_arg_departamental">Por departamento</label>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>

                            <div class="card-footer text-muted">
                                <a type="button" class="w-100 btn btn-lg btn-success" href="new_dashboard.html">Continuar</a>
                            </div>

                        </div>
                    </div>
    
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-1">
                                <h4 class="my-0 fw-normal">Nivel Provincial</h4>
                            </div>
                            <div class="card-body">
                                <img class="card-img-top" src="./assets/arg.png" alt="">
    
                                <p class="text-center fs-6 mt-3 mb-4">
                                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima, eius esse! Nesciunt illum non quam.
                                </p>
    
                                <div class="d-grid gap-2 d-md-block">
                                    <div class="row row-cols-2 justify-content-md-center">
                                        <div class="col d-flex pb-2 flex-column">
                                            <input type="radio" class="btn-check" name="btnradio_nivel_provincial" id="btnradio_arg_seccional" autocomplete="off">
                                            <label class="btn btn-outline-secondary" for="btnradio_arg_seccional">Por departamento</label>
                                        </div>
                                        <div class="col d-flex pb-2 flex-column">
                                            <input type="radio" class="btn-check" name="btnradio_nivel_provincial" id="btnradio_arg_circuito" autocomplete="off">
                                            <label class="btn btn-outline-secondary" for="btnradio_arg_circuito">Por circuito</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer text-muted">
                                <a type="button" class="w-100 btn btn-lg btn-success" href="new_dashboard.html">Continuar</a>
                            </div>

                        </div>
                    </div>
    
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-1">
                                <h4 class="my-0 fw-normal">Nivel Departamental</h4>
                                
                            </div>
                            <div class="card-body">
                                <img class="card-img-top" src="./assets/arg.png" alt="">
    
                                <p class="text-center fs-6 mt-3 mb-4">
                                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima, eius esse! Nesciunt illum non quam.
                                </p>

                                <div class="d-grid gap-2 d-md-block">
                                    <div class="row row-cols-1 justify-content-md-center">
                                        <div class="col d-flex pb-2 flex-column">
                                            <input type="radio" class="btn-check" name="btnradio_nivel_departamental" id="btnradio_arg_p_circuito" autocomplete="off">
                                            <label class="btn btn-outline-secondary" for="btnradio_arg_p_circuito">Por circuito</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer text-muted">
                                <a type="button" class="w-100 btn btn-lg btn-success" href="new_dashboard.html">Continuar</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </main>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
        crossorigin="anonymous">
        </script>



    </body>
</html>